/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_plugins_kkuevent */

#ifndef _Included_com_androidex_plugins_kkuevent
#define _Included_com_androidex_plugins_kkuevent
#ifdef __cplusplus
extern "C" {
#endif

jint Uevent_OnLoad(JavaVM* vm, void* reserved);
void Uevent_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    find
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_native_1uevent_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_native_1uevent_1read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_plugins_kkuevent
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_plugins_kkuevent_native_1uevent_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
